baseURL = "https://gopkumr.gihub.io/"
languageCode = "en-au"
title = "Beneath Abstraction"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Gopakumar"
  description = "Learn. Share. Grow"
  github = "gopkumr"
  facebook = ""
  twitter = "gopkumr"
  linkedin = "gopkumr"
  instagram = "gopkumr"
  tumblr = ""
  email = "gopakumar.r@live.com"
  url = "https://gopkumr.gihub.io/"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "Australia"
  avatar = "https://avatars.githubusercontent.com/u/1662197?s=400&u=d1fd525c38f21c760b5f73d3046d9cdee3debcc3&v=4"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]