baseURL = "https://www.beneathabstraction.com/"
languageCode = "en-au"
title = "Beneath Abstraction"
theme = "github-style"
googleAnalytics = "UA-171421715-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Gopakumar"
  description = "Technical Lead, Developer and Microsoft tech enthusiast"
  github = "gopkumr"
  facebook = ""
  twitter = "gopkumr"
  linkedin = "gopkumr"
  instagram = "gopkumr"
  tumblr = ""
  email = "gopakumar.r@live.com"
  url = "https://www.beneathabstraction.com/"
  keywords = "blog, techical blog, Microsoft .Net, Csharp, asp.net, docker, mvc, kubernetes, pulumi"
  rss = true
  lastmod = false
  favicon = "/images/github.png"
  location = "Australia"
  avatar = "https://avatars.githubusercontent.com/u/1662197?s=400&u=d1fd525c38f21c760b5f73d3046d9cdee3debcc3&v=4"

 [[params.links]]
    title = "dev.to"
    href = "https://dev.to/gopkumr"
    icon = "/images/dev_to_icon.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]